Repository Mindera/Alicerce, pull requests merged in 2018-11, with the labels that each got.

#173 Improve cancellation handling in `NetworkStore`'s
  Sources/Network/URLSessionNetworkStack.swift
  Sources/Shared/Cancelable.swift
  Sources/Stores/NetworkPersistableStore.swift
  Sources/Stores/NetworkStore.swift
  Tests/AlicerceTests/Network/Mocks/MockNetworkStack.swift
  Tests/AlicerceTests/Shared/CancelableBagTestCase.swift
  Tests/AlicerceTests/Stores/NetworkPersistableStoreTestCase.swift
  Tests/AlicerceTests/Stores/NetworkStoreTestCase.swift
Labels: bug, enhancement

#174 Propagate errors on .cancelled network store errors
  Sources/Stores/NetworkPersistableStore.swift
  Sources/Stores/NetworkStore.swift
  Tests/AlicerceTests/Stores/NetworkPersistableStoreTestCase.swift
  Tests/AlicerceTests/Stores/NetworkStoreTestCase.swift
Labels: enhancement

#133 Add SwiftLint to the project
  .swiftlint.yml
  .travis.yml
  Alicerce.playground/Pages/Network.xcplaygroundpage/Contents.swift
  Alicerce.xcodeproj/project.pbxproj
  Alicerce.xcodeproj/xcshareddata/xcschemes/Alicerce.xcscheme
  Brewfile
  Sources/Analytics/Trackers/Analytics+MultiTracker.swift
  Sources/Analytics/Trackers/AnalyticsTracker.swift
  Sources/DeepLinking/Route+Tree.swift
  Sources/DeepLinking/Router.swift
  Sources/Extensions/Dictionary.swift
  Sources/Extensions/Sequence.swift
  Sources/Extensions/String.swift
  Sources/Logging/Destinations/Log+ConsoleLogDestination.swift
  Sources/Logging/Destinations/Log+FileLogDestination.swift
  Sources/Logging/ItemFormatters/Log+StringLogItemFormatter.swift
  Sources/Logging/LevelFormatters/Log+BashLogLevelFormatter.swift
  Sources/Logging/LevelFormatters/Log+DefaultLogLevelFormatter.swift
  Sources/Logging/Loggers/Log+DefaultLogger.swift
  Sources/Logging/Loggers/Logger.swift
  Sources/Logging/Loggers/ModuleLogger.swift
  Sources/Network/HTTP.swift
  Sources/Network/JSON+Mappable.swift
  Sources/Network/JSON.swift
  Sources/Network/Network.swift
  Sources/Network/Pinning/Data+SPKIHash.swift
  Sources/Network/Pinning/PublicKeyAlgorithm.swift
  Sources/Network/Pinning/ServerTrustEvaluator+Configuration.swift
  Sources/Network/Pinning/ServerTrustEvaluator.swift
  Sources/Network/Serialize.swift
  Sources/Network/URLSessionNetworkStack.swift
  Sources/PerformanceMetrics/PerformanceMetrics.swift
  Sources/Persistence/CoreData/CoreDataEntity.swift
  Sources/Persistence/CoreData/CoreDataStack+ManagedObjectReflectable.swift
  Sources/Persistence/CoreData/CoreDataStack.swift
  Sources/Persistence/CoreData/NSManagedObjectContext+CoreDataStack.swift
  Sources/Persistence/CoreData/NestedContextCoreDataStack.swift
  Sources/Persistence/CoreData/SiblingContextCoreDataStack.swift
  Sources/Persistence/DiskMemoryPersistenceStack.swift
  Sources/Persistence/Persistence.swift
  Sources/Persistence/PersistencePerformanceMetricsTracker.swift
  Sources/Resource/ResourceRetry.swift
  Sources/Stores/NetworkPersistableStore.swift
  Sources/UIKit/TableViewCell.swift
  Sources/UIKit/TableViewHeaderFooterView.swift
  Sources/UIKit/UIColor.swift
  Sources/UIKit/UIViewController.swift
  Sources/Utils/AssertDumpsEqual.swift
  Sources/Utils/Box.swift
  Sources/Utils/Lock.swift
  Sources/Utils/ServiceLocator.swift
  Sources/View/ReusableView.swift
Labels: enhancement, project setup
