Repository Mindera/Alicerce, pull requests merged in 2018-06, with the labels that each got.

#142 Add documentation for the network layer. 📄
  Documentation/Network.md
  README.md
Labels: documentation

#146 Use Result in the network layer.
  Alicerce.playground/Pages/Network.xcplaygroundpage/Contents.swift
  Alicerce.playground/Pages/Playground.xcplaygroundpage/Contents.swift
  Alicerce.playground/contents.xcplayground
  Alicerce.xcworkspace/contents.xcworkspacedata
  Documentation/Network.md
  Sources/Network/Network.swift
  Sources/Network/NetworkAuthenticator.swift
  Sources/Network/URLSessionNetworkStack.swift
  Sources/Stores/NetworkPersistableStore.swift
  Sources/Stores/NetworkStore.swift
  Tests/AlicerceTests/Network/MockNetworkStack.swift
  Tests/AlicerceTests/Network/URLSessionNetworkStackTestCase.swift
  Tests/AlicerceTests/Stores/StoreTestCase.swift
Labels: enhancement

#145 Logging improvements (Modules, Metadata, others)
  Alicerce.xcodeproj/project.pbxproj
  Sources/Extensions/DispatchQueue.swift
  Sources/Extensions/Thread.swift
  Sources/Logging/Destinations/Log+ConsoleLogDestination.swift
  Sources/Logging/Destinations/Log+FileLogDestination.swift
  Sources/Logging/ItemFormatters/Log+JSONLogItemFormatter.swift
  Sources/Logging/ItemFormatters/Log+StringLogItemFormatter.swift
  Sources/Logging/LevelFormatters/Log+BashLogLevelFormatter.swift
  Sources/Logging/LevelFormatters/Log+DefaultLogLevelFormatter.swift
  Sources/Logging/Log+ConsoleLogDestination.swift
  Sources/Logging/Log+DefaultLogItemLevelFormatter.swift
  Sources/Logging/Log+DefaultLogger.swift
  Sources/Logging/Log+FileLogDestination.swift
  Sources/Logging/Log+Item.swift
  Sources/Logging/Log+JSONLogItemFormatter.swift
  Sources/Logging/Log.swift
  Sources/Logging/Protocols/LogDestination.swift
  Sources/Logging/Protocols/LogItemFormatter.swift
  Sources/Logging/Protocols/LogItemLevelFormatter.swift
  Sources/Logging/Protocols/LogLevelFormatter.swift
  Sources/Logging/Protocols/LogModule.swift
  Sources/Logging/Protocols/Logger.swift
  Tests/AlicerceTests/Extensions/DataTestCase.swift
  Tests/AlicerceTests/Extensions/DispatchQueueTestCase.swift
  Tests/AlicerceTests/Extensions/OptionalTests.swift
  Tests/AlicerceTests/Extensions/ThreadTestCase.swift
  Tests/AlicerceTests/Logging/DefaultLoggerTestCase.swift
  Tests/AlicerceTests/Logging/Destinations/ConsoleLogDestinationTestCase.swift
  Tests/AlicerceTests/Logging/Destinations/FileLogDestinationTestCase.swift
  Tests/AlicerceTests/Logging/Destinations/LogDestinationTestCase.swift
  Tests/AlicerceTests/Logging/Destinations/MockLogDestination.swift
  Tests/AlicerceTests/Logging/ItemFormatters/JSONLogItemFormatterTestCase.swift
  Tests/AlicerceTests/Logging/ItemFormatters/MockLogItemFormatter.swift
  Tests/AlicerceTests/Logging/ItemFormatters/StringLogItemFormatterTestCase.swift
  Tests/AlicerceTests/Logging/LevelFormatters/BashLogLevelFormatterTestCase.swift
  Tests/AlicerceTests/Logging/LevelFormatters/DefaultLogLevelFormatterTestCase.swift
  Tests/AlicerceTests/Logging/LevelFormatters/MockLogLevelFormatter.swift
  Tests/AlicerceTests/Logging/Log+Item.swift
  Tests/AlicerceTests/Logging/LoggerTestCase.swift
Labels: enhancement, new feature
