Repository Mindera/Alicerce, pull requests merged in 2018-04, with the labels that each got.

#113 Fixed query build with existing query items
  Alicerce.xcodeproj/project.pbxproj
  Alicerce.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Sources/Resource/NetworkResource.swift
  Tests/AlicerceTests/Network/ResourceTestCase.swift
Labels: bug, foundation

#114 Add `Atomic` ☢️ and `Lock` 🔒
  Alicerce.xcodeproj/project.pbxproj
  Sources/Utils/Atomic.swift
  Sources/Utils/Lock.swift
  Tests/AlicerceTests/Utils/AtomicTestCase.swift
  Tests/AlicerceTests/Utils/LockTestCase.swift
  Tests/AlicerceTests/Utils/PthreadLockTestCase.swift
  Tests/AlicerceTests/Utils/UnfairLockTestCase.swift
Labels: new feature

#116 Improve README.md, prepare for 0.1.0 🚀
  .travis.yml
  Alicerce.podspec
  Alicerce.xcodeproj/project.pbxproj
  README.md
Labels: enhancement, new feature

#117 Migrate to Swift 4.1 and Xcode 9.3
  .travis.yml
  Alicerce.podspec
  Alicerce.xcodeproj/project.pbxproj
  Alicerce.xcodeproj/xcshareddata/xcschemes/Alicerce.xcscheme
  Sources/Utils/Lock.swift
  Tests/AlicerceTests/Utils.swift
Labels: enhancement, new feature

#120 Revise `Dictionary` and `Sequence` utils API's
  Alicerce.xcodeproj/project.pbxproj
  Sources/Analytics/Analytics.swift
  Sources/Extensions/Dictionary.swift
  Sources/Extensions/Sequence.swift
  Tests/AlicerceTests/Extensions/DictionaryTests.swift
  Tests/AlicerceTests/Extensions/SequenceTests.swift
Labels: enhancement, tests
