Repository Mindera/Alicerce, pull requests merged in 2019-04, with the labels that each got.

#186 Add configurable internal logger 📝
  Alicerce.xcodeproj/project.pbxproj
  Sources/Logging/Destinations/Log+ConsoleLogDestination.swift
  Sources/Logging/Destinations/LogDestination.swift
  Sources/Logging/Destinations/MetadataLogDestination.swift
  Sources/Logging/Log.swift
  Sources/Logging/Loggers/Log+DefaultLogger.swift
  Sources/Logging/Loggers/Log+DummyLogger.swift
  Sources/Logging/Loggers/Logger.swift
  Sources/Logging/Loggers/MetadataLogger.swift
  Sources/Logging/Loggers/ModuleLogger.swift
  Sources/Persistence/CoreData/NSManagedObjectContext+CoreDataStack.swift
  Sources/Persistence/DiskMemoryPersistenceStack.swift
  Sources/Stores/NetworkPersistableStore.swift
  Tests/AlicerceTests/Logging/Destinations/MockMetadataLogDestination.swift
  Tests/AlicerceTests/Logging/Loggers/DefaultLoggerTestCase.swift
  Tests/AlicerceTests/Logging/Loggers/DummyLoggerTestCase.swift
  Tests/AlicerceTests/Logging/Loggers/LoggerTestCase.swift
  Tests/AlicerceTests/Logging/Loggers/MetadataLoggerTestCase.swift
  Tests/AlicerceTests/Logging/Loggers/ModuleLoggerTestCase.swift
  Tests/AlicerceTests/Persistence/DiskMemoryPersistenceTestCase.swift
Labels: enhancement, new feature

#187 Make `APIError`'s great again ✊
  Sources/Network/Network.swift
  Sources/Network/URLSessionNetworkStack.swift
  Sources/Resource/NetworkResource.swift
  Sources/Resource/Resource.swift
  Tests/AlicerceTests/Network/NetworkTestCase.swift
  Tests/AlicerceTests/Network/URLSessionNetworkStackTestCase.swift
  Tests/AlicerceTests/PerformanceMetrics/NetworkStorePerformanceMetricsTrackerTestCase.swift
  Tests/AlicerceTests/Resource/HTTPNetworkResourceTestCase.swift
  Tests/AlicerceTests/Resource/MockResource.swift
Labels: enhancement, new feature

#188 Split `Resource` (and friends) into small protocols 👨‍👩‍👧‍👦
  Alicerce.xcodeproj/project.pbxproj
  Sources/Network/Network.swift
  Sources/Network/NetworkStack.swift
  Sources/Network/RequestAuthenticator.swift
  Sources/Network/URLSessionNetworkStack.swift
  Sources/Resource/AuthenticatedHTTPNetworkResource.swift
  Sources/Resource/AuthenticatedRequestResource.swift
  Sources/Resource/BaseRequestResource.swift
  Sources/Resource/CodableResource.swift
  Sources/Resource/EmptyExternalResource.swift
  Sources/Resource/ExternalErrorDecoderResource.swift
  Sources/Resource/HTTPNetworkResource.swift
  Sources/Resource/NetworkResource.swift
  Sources/Resource/RequestResource.swift
  Sources/Resource/Resource.swift
  Sources/Resource/RetryableResource.swift
  Sources/Resource/StrategyFetchResource.swift
  Sources/Shared/Retry.swift
  Sources/Stores/NetworkPersistableStore.swift
  Sources/Stores/NetworkStore.swift
  Sources/Stores/NetworkStorePerformanceMetricsTracker.swift
  Tests/AlicerceTests/Network/Mocks/MockNetworkStack.swift
  Tests/AlicerceTests/Network/Mocks/MockRequestAuthenticator.swift
  Tests/AlicerceTests/Network/NetworkTestCase.swift
  Tests/AlicerceTests/Network/URLSessionNetworkStackTestCase.swift
  Tests/AlicerceTests/PerformanceMetrics/NetworkStorePerformanceMetricsTrackerTestCase.swift
  Tests/AlicerceTests/Resource/AuthenticatedHTTPNetworkResourceTestCase.swift
  Tests/AlicerceTests/Resource/HTTPNetworkResourceTestCase.swift
  Tests/AlicerceTests/Resource/MockResource.swift
  Tests/AlicerceTests/Resource/NetworkResourceTestCase.swift
  Tests/AlicerceTests/Resource/RetryableResourceTestCase.swift
  Tests/AlicerceTests/Shared/RetryTestCase.swift
  Tests/AlicerceTests/Stores/NetworkPersistableStoreTestCase.swift
  Tests/AlicerceTests/Stores/NetworkStoreTestCase.swift
Labels: enhancement, foundation, new feature

#189 Rename `DefaultLogger` to `MultiLogger` 📄
  Alicerce.xcodeproj/project.pbxproj
  Sources/Logging/Loggers/Log+DefaultLogger.swift
  Tests/AlicerceTests/Logging/Loggers/MultiLoggerTestCase.swift
Labels: enhancement

#190 Fix Network playground 🎳
  Alicerce.playground/Pages/Network.xcplaygroundpage/Contents.swift
Labels: bug, documentation

#191 Multiple clean ups and minor additions 🧹
  Alicerce.playground/Pages/Network.xcplaygroundpage/Contents.swift
  Alicerce.xcodeproj/project.pbxproj
  Sources/Analytics/Trackers/Analytics+MultiTracker.swift
  Sources/Analytics/Trackers/AnalyticsTracker.swift
  Sources/DeepLinking/Route+Component.swift
  Sources/DeepLinking/Route+Tree.swift
  Sources/DeepLinking/Router.swift
  Sources/Logging/Loggers/Log+MultiLogger.swift
  Sources/Network/NetworkStack.swift
  Sources/Network/Pinning/ServerTrustEvaluator.swift
  Sources/Network/RequestAuthenticator.swift
  Sources/Network/URLSessionNetworkStack.swift
  Sources/PerformanceMetrics/PerformanceMetrics.swift
  Sources/PerformanceMetrics/Trackers/PerformanceMetrics+MultiTracker.swift
  Sources/PerformanceMetrics/Trackers/PerformanceMetricsTracker.swift
  Sources/Persistence/CoreData/CoreDataEntity.swift
  Sources/Persistence/CoreData/CoreDataStack+CRUD.swift
  Sources/Persistence/CoreData/CoreDataStack+Factories.swift
  Sources/Persistence/CoreData/CoreDataStack.swift
  Sources/Persistence/CoreData/NSPersistentStoreCoordinator+CoreDataStack.swift
  Sources/Persistence/CoreData/NestedContextCoreDataStack.swift
  Sources/Persistence/CoreData/SiblingContextCoreDataStack.swift
  Sources/Persistence/DiskMemoryPersistenceStack.swift
  Sources/Persistence/PersistenceStack.swift
  Sources/Resource/EmptyExternalResource.swift
  Sources/Resource/HTTPResourceEndpoint.swift
  Sources/Utils/Atomic.swift
  Sources/Utils/Lock.swift
  Sources/View/NibView.swift
  Sources/View/ReusableView.swift
  Tests/AlicerceTests/Analytics/MockAnalyticsTracker.swift
  Tests/AlicerceTests/Extensions/StringTestCase.swift
  Tests/AlicerceTests/Extensions/URLRequestTestCase.swift
  Tests/AlicerceTests/Network/HTTPTestCase.swift
  Tests/AlicerceTests/Network/Mocks/MockAuthenticationChallengeHandler.swift
  Tests/AlicerceTests/Network/Mocks/MockNetworkStack.swift
  Tests/AlicerceTests/Network/Mocks/MockURLSession.swift
  Tests/AlicerceTests/Network/Pinning/CertificateUtils.swift
  Tests/AlicerceTests/PerformanceMetrics/PersistencePerformanceMetricsTrackerTestCase.swift
  Tests/AlicerceTests/Persistence/CoreData/TestEntity+Utils.swift
  Tests/AlicerceTests/Persistence/DiskMemoryPersistenceTestCase.swift
  Tests/AlicerceTests/Resource/EmptyExternalResourceTestCase.swift
  Tests/AlicerceTests/Resource/MockResource.swift
  Tests/AlicerceTests/Utils.swift
Labels: enhancement

#192 Add a Gitter chat badge to README.md
  README.md
Labels: documentation, project setup
