Repository Mindera/Alicerce, pull requests merged in 2020-01, with the labels that each got.

#207 Implement backtracking on Router match ⏪
  Alicerce.xcodeproj/project.pbxproj
  Sources/DeepLinking/ApplicationRouter.swift
  Sources/DeepLinking/Route+Component.swift
  Sources/DeepLinking/Route+Tree.swift
  Sources/DeepLinking/Route+TrieNode.swift
  Sources/DeepLinking/Route+TrieRouter.swift
  Sources/DeepLinking/Route.swift
  Sources/DeepLinking/Router.swift
  Tests/AlicerceTests/DeepLinking/Route+ComponentTests.swift
  Tests/AlicerceTests/DeepLinking/Route+Tree_AddTests.swift
  Tests/AlicerceTests/DeepLinking/Route+Tree_DescriptionTests.swift
  Tests/AlicerceTests/DeepLinking/Route+Tree_InitTests.swift
  Tests/AlicerceTests/DeepLinking/Route+Tree_MatchTests.swift
  Tests/AlicerceTests/DeepLinking/Route+Tree_RemoveTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieNode_AddTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieNode_InitTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieNode_IsEmptyAndDescriptionTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieNode_MatchTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieNode_RemoveTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieNode_TestUtils.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieRouter_DescriptionTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieRouter_RegisterTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieRouter_RouteTests.swift
  Tests/AlicerceTests/DeepLinking/Route+TrieRouter_UnregisterTests.swift
  Tests/AlicerceTests/DeepLinking/TreeRouterTests.swift
  Tests/AlicerceTests/TestUtils.swift
Labels: enhancement, foundation, new feature

#210 Auto layout DSL
  Alicerce.podspec
  Alicerce.xcodeproj/project.pbxproj
  README.md
  Sources/AutoLayout/Array+ConstrainableProxy.swift
  Sources/AutoLayout/Constrain.swift
  Sources/AutoLayout/ConstrainableProxy.swift
  Sources/AutoLayout/ConstraintRelation.swift
  Sources/AutoLayout/LayoutGuideProxy.swift
  Sources/AutoLayout/LayoutItem.swift
  Sources/AutoLayout/NSLayoutConstraint+Helpers.swift
  Sources/AutoLayout/ViewProxy.swift
  Tests/AlicerceTests/AutoLayout/BaseConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/BottomConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/CenterConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/CenterXConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/CenterYConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/EdgesConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/FirstBaselineConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/HeightConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/LastBaselineConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/LeadingConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/LeadingTrailingConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/LeftConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/NSLayoutConstraint+TestHelpers.swift
  Tests/AlicerceTests/AutoLayout/NSLayoutConstraintTestCase.swift
  Tests/AlicerceTests/AutoLayout/RightConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/SizeConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/TopBottomConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/TopConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/TrailingConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/WidthConstrainableProxyTestCase.swift
  Tests/AlicerceTests/AutoLayout/XCTAssertConstraint.swift
Labels: new feature, ui

#213 Set `public` access control on the Auto Layout's public API methods
  Sources/AutoLayout/Array+ConstrainableProxy.swift
  Sources/AutoLayout/Constrain.swift
  Sources/AutoLayout/ConstrainableProxy.swift
  Sources/AutoLayout/ConstraintRelation.swift
  Sources/AutoLayout/LayoutGuideProxy.swift
  Sources/AutoLayout/LayoutItem.swift
  Sources/AutoLayout/NSLayoutConstraint+Helpers.swift
  Sources/AutoLayout/ViewProxy.swift
Labels: bug

#212 Remove then function
  Sources/Extensions/Foundation/Optional.swift
  Tests/AlicerceTests/Extensions/Foundation/OptionalTests.swift
Labels: maintenance
