Repository Mindera/Alicerce, pull requests merged in 2021-05, with the labels that each got.

#233 Migrate to GitHub Actions 🤖
  .github/workflows/ci.yml
  .github/workflows/pod-lint.yml
  .github/workflows/release.yml
  .github/workflows/spm.yml
  .travis.yml
  Alicerce.xcodeproj/project.pbxproj
  Gemfile
  Gemfile.lock
Labels: enhancement, maintenance, project setup

#232 Add single module SPM product 💧
  .swiftpm/xcode/xcshareddata/xcschemes/Alicerce (SPM).xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceAnalytics.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceAutoLayout.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceCore.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceDeepLinking.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceExtensions.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceLogging.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceNetwork.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceObservers.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicercePerformanceMetrics.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicercePersistence.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceStackOrchestrator.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/AlicerceView.xcscheme
  Package.swift
  SingleModuleSources
Labels: enhancement, maintenance, project setup, question

#235 Clean up README and bump version in Info.plist 💄
  README.md
  Resources/Info.plist
Labels: documentation, maintenance

#236 Unify Release and CI workflows 🤝
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: bug, maintenance, project setup

#237 Remove old `UIView` extensions for auto-layout constraints 📐
  Alicerce.xcodeproj/project.pbxproj
  Sources/Extensions/UIKit/UIView.swift
  Tests/AlicerceTests/Extensions/UIKit/UIViewConstraintTestCase.swift
Labels: enhancement

#238 Change UInt instances to Int
  Sources/Logging/Log.swift
  Sources/Logging/Loggers/Log+DummyLogger.swift
  Sources/Logging/Loggers/Log+MultiLogger.swift
  Sources/Logging/Loggers/Logger.swift
  Sources/Logging/Loggers/ModuleLogger.swift
  Sources/Persistence/DiskMemoryPersistenceStack.swift
  Sources/Persistence/PersistencePerformanceMetricsTracker.swift
  Sources/Utils/Token.swift
  Tests/AlicerceTests/Logging/Loggers/LoggerTestCase.swift
  Tests/AlicerceTests/Logging/Loggers/ModuleLoggerTestCase.swift
  Tests/AlicerceTests/Persistence/DiskMemoryPersistenceTestCase.swift
  Tests/AlicerceTests/Persistence/PersistencePerformanceMetricsTrackerTestCase.swift
Labels: enhancement, foundation, maintenance
